# Generated by Django 5.1.6 on 2025-02-09 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.country')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True)),
                ('lead_status', models.CharField(choices=[('Pending', 'Pending'), ('In-progress', 'In-progress'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.country')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.country')),
                ('managed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_photo', models.ImageField(upload_to='devices/')),
                ('currency', models.CharField(max_length=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('sourced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='WalkIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('walk_in_date_time', models.DateTimeField(auto_now_add=True)),
                ('token_number', models.IntegerField(unique=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.device')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.lead')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255)),
                ('allowed_devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.device')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('section_image', models.ImageField(upload_to='sections/')),
                ('section_html_content', models.TextField()),
                ('section_order', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.webpage')),
            ],
        ),
    ]
